---
title: "Solent region: Test Maps"
author: "Meghan Kinglsey-Walsh"
date: 'Last run at: `r Sys.time()`'
output:
  bookdown::html_document2:
    fig_caption: yes
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 4
    toc_float: TRUE
  bookdown::pdf_document2:
    toc: yes
    fig_caption: yes
    number_sections: yes
  bookdown::word_document2: 
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 4
    fig_width: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) # set this to FALSE if you don't want the code in the final output

# useful R libraries
library(ggplot2)
library(readr)
library(dplyr)

# GIS libraries
library(raster)
library(sf)
library(spData)
library(spDataLarge)

dataFolder<-"/Users/megha/Desktop/1. Uni/Masters/Project/Mapping Code/data/" # default for Meghan
user <- Sys.info()[[7]] # who are we logged in as?
if(user == "ben"){
  dataFolder <- path.expand("~/University of Southampton/HCC Energy Landscape Mapping project - Documents/General/data/")
}

# this will not print anything out when knitted due to the include=FALSE setting in the chunk header
message("User: ", user)
message("dataFolder: ", dataFolder)
```


# Mapping the Local Authority
##Mapping Domestic Electricity Consumption
```{r loading in Local Authority electricity consumption data}
#inFile <-paste0(dataFolder, "energy/Subnational_electricity_consumption_statistics_2019.csv")
#la_elecData <- readr::read_csv(inFile)
#summary(la_elecData)
```

```{r Loading in the Boundary Data for local authorities we are intrested in}
# geo_query <- "https://ons-inspire.esriuk.com/arcgis/rest/services/Administrative_Boundaries/Local_Authority_Districts_December_2018_Boundaries_UK_BGC/MapServer/0/query?where=lad18nm%20IN%20(%27Southampton%27,%27Portsmouth%27,%27Winchester%27,%27Eastleigh%27,%27Isle%20of%20Wight%27,%27Fareham%27,%27Gosport%27,%27Test%20Valley%27,%27East%20Hampshire%27,%27Havant%27,%27New%20Forest%27,%27Hart%27,%27Basingstoke%20and%20Deane%27)&outFields=lad18cd,lad18nm,long,lat&outSR=4326&f=geojson"
# #This only includes the ones we are interested in i.e the Solent
# message("Loading LA geometry from ONS Open Geography API") #Specifying the location message
# la_sf_data <- sf::st_read(geo_query)

# The above is very clever but it takes time
# Load from file
#la_shpFile <- paste0(dataFolder, "/boundaries/LA/la_solent.shp")
#la_sf_data <- sf::st_read(la_shpFile)
#]head(la_sf_data)
```

```{r Mapping the local authority electricty consumption}
#la_elecData$lad18cd <- la_elecData$`LA Code`#Creating a variable with the local authority code in the same name of the consumption data
#la_merged_sf <- merge(la_sf_data, la_elecData)#Merge the local Authority boundaries and the consumption data
#ggplot2::ggplot(la_merged_sf) +
 # geom_sf(aes(fill = Total_GWh))+scale_fill_gradient(low="green",high="red")

```
## Mapping Transport
### Freight
```{r Loading the  Freight Transport consumption data for the Local Autority}
#inFile <-paste0(dataFolder, "energy/Local Authority level Transport data.csv")
#la_Transport <- readr::read_csv(inFile)
#summary(la_Transport)
#head(la_Transport)
```

```{r Mapping the local authority energy consumption (Freight)}

#la_Transport$lad18cd <- la_Transport$Code # Creating a variable with the local authority code in the same name of the consumption data
#la_merged_Transp <- merge(la_sf_data, la_Transport)# Merge the local Authority boundaries and the Transport data
#ggplot2::ggplot(la_merged_Transp) +
 # geom_sf(aes(fill = Freight)) +
  #scale_fill_gradient(name = "Freight: Thousand tonnes of oil equivalent (ktoe)", low="green",high="red")
```

### Personal
Note: this data is not per household/person so it will correlate (to some extent) with population size.

```{r Mapping the local authority energy consumption (Personal)}
# re-use the merged dataset
#ggplot2::ggplot(la_merged_Transp) +
 # geom_sf(aes(fill = Personal)) +
  #scale_fill_gradient(name = "Personal: Thousand tonnes of oil equivalent (ktoe)", low="green",high="red") 
```
## Mapping Fuel Poverty 
### 2019

```{r Loading in the 2019 Local Authority Fuel Poverty Data}
#inFile<-paste0(dataFolder, "Fuel Poverty/2019 LA_Fuel_Poverty.csv")
#la_fuelpov_2019<-readr::read_csv(inFile)
#head(la_fuelpov_2019)
```
```{r Mapping Local Authority Fuel Poverty 2019}
#la_fuelpov_2019$lad18cd <- la_fuelpov_2019$`Area Code` # Creating a variable with the local authority code in the same name 
#la_merged_Fuelpov2019 <- merge(la_sf_data, la_fuelpov_2019)# Merge the local Authority boundaries and the Fuel Poverty data
#la_merged_Fuelpov2019$pcFP <- as.numeric(la_merged_Fuelpov2019$`Proportion of households fuel poor (%)`) # convert to numeric from char - why does it load as char??
#ggplot2::ggplot(la_merged_Fuelpov2019) +
 # geom_sf(aes(fill = pcFP)) +
  #scale_fill_gradient(name = "Proportion of households fuel poor (%) 2019", low="green",high="red")
```
###2018
```{r Loading in the 2018 Local Authority Fuel Poverty Data}
#inFile<-paste0(dataFolder, "Fuel Poverty/2018 LA_Fuel_Poverty.csv")
#la_fuelpov_2018<-readr::read_csv(inFile)
#head(la_fuelpov_2018)
```
```{r Mapping Local Authority Fuel Poverty 2018}
#la_fuelpov_2018$lad18cd <- la_fuelpov_2018$`Area Code` # Creating a variable with the local authority code in the same name 
#la_merged_Fuelpov2018 <- merge(la_sf_data, la_fuelpov_2018)# Merge the local Authority boundaries and the Fuel Poverty data
#la_merged_Fuelpov2018$pcFP <- as.numeric(la_merged_Fuelpov2018$`Proportion of households fuel poor (%)`) # convert to numeric from char - why does it load as char??
#ggplot2::ggplot(la_merged_Fuelpov2019) +
 # geom_sf(aes(fill = pcFP)) +
  #scale_fill_gradient(name = "Proportion of households fuel poor (%) 2018", low="green",high="red")
```

### Difference in proportion Fuel Poverty 2012 to 2018 

```{r Creating the difference in proportion variable}
#Green indicates a smaller increase in fuel poverty from 2012 to 2018
#Red indicates an increase in fuel poverty from 2012 to 2018
#2018 has to be used as the metric for measuring fuel poverty changed in 2019
#fp_LA_2012_df <- readr::read_csv(paste0(dataFolder, "/Fuel Poverty/2012 LA_Fuel_Poverty.csv"))
#fp_LA_2018_df <- readr::read_csv(paste0(dataFolder, "/Fuel Poverty/2018 LA_Fuel_Poverty.csv"))
#fp_LA_2012_df$pc2012la <- fp_LA_2012_df$`Proportion of households fuel poor (%) 2012`
#fp_LA_2018_df$pc2018la <- fp_LA_2018_df$`Proportion of households fuel poor (%)`
#merged_dfla <- merge(fp_LA_2012_df, fp_LA_2018_df, by = "LA Code", all = TRUE)
#names(merged_dfla)
#merged_dfla$pc_diff <-as.numeric(merged_dfla$pc2018la)- merged_dfla$pc2012la
#summary(merged_dfla)
```

```{r Mapping the difference in fuel poverty from 2012 to 2018}
#merged_dfla$lad18nm <- merged_dfla$`LA Code` # Creating a variable with the local authority code in the same name 
#la_Fuelpov20182012dif <- merge(la_sf_data, merged_dfla) # Merge the local Authority boundaries and the Fuel Poverty data
#ggplot2::ggplot(la_Fuelpov20182012dif) +
 # geom_sf(aes(fill = pc_diff)) +
  #scale_fill_gradient(name = " Difference in proportion of households fuel poor (%)", low="green", high="red") +
#labs(caption="Solent (all LA)")
```

