---
title: "LOSA Fuel Poverty maps"
author: "Meghan Kinglsey-Walsh"
date: 'Last run at: `r Sys.time()`'
output:
  bookdown::html_document2:
    fig_caption: yes
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 4
    toc_float: TRUE
  bookdown::pdf_document2:
    toc: yes
    fig_caption: yes
    number_sections: yes
  bookdown::word_document2: 
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 4
    fig_width: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) # set this to FALSE if you don't want the code in the final output

# useful R libraries
library(ggplot2)
library(readr)
library(dplyr)

# GIS libraries
library(raster)
library(sf)
library(spData)
library(spDataLarge)

dataFolder<-"/Users/megha/Desktop/1. Uni/Masters/Project/Mapping Code/data/" # default for Meghan
user <- Sys.info()[[7]] # who are we logged in as?
if(user == "ben"){
  dataFolder <- path.expand("~/University of Southampton/HCC Energy Landscape Mapping project - Documents/General/data/")
}

# this will not print anything out when knitted due to the include=FALSE setting in the chunk header
message("User: ", user)
message("dataFolder: ", dataFolder)
```


# Mapping the Lower Layer Super Output Area (LSOA)
```{r Loading in boundary data for the LSOA}
#The LSOA boundaries for the Solent have been pre-downloaded
inf<-paste0(dataFolder, "boundaries/LSOA/lsoa_solent.shp")
message ("Loading LSOA boundaries from file")
lsoa_sf_data <- sf::read_sf(inf)
head(lsoa_sf_data)
table(lsoa_sf_data$LAD11NM)#How many LSOAs are there in each LA
```

### Mapping Fuel Poverty
#### 2019
```{r Loading in the LSOA 2019 Fuel Poverty data}
inFile<-paste0(dataFolder, "Fuel Poverty/2019 LSOA_Fuel_Poverty.csv")
lsoa_fuelpov_2019<-readr::read_csv (inFile)
head(lsoa_fuelpov_2019)
```

```{r Mapping the LSOA 2019 Fuel Poverty}
lsoa_fuelpov_2019$LSOA11CD <- lsoa_fuelpov_2019$"LSOA Code" #creating a variable with the LSOA code in the same name as in sf_data
lsoa_fuelpov_2019_merged <- merge(lsoa_sf_data, lsoa_fuelpov_2019) #merging these
# as above - why does it load as a char?
lsoa_fuelpov_2019_merged$pcFP <- as.numeric(lsoa_fuelpov_2019_merged$`Proportion of households fuel poor (%)`)
ggplot2::ggplot(lsoa_fuelpov_2019_merged) +
  geom_sf(aes(fill=pcFP))+ 
  scale_fill_continuous(name="Proportion of households fuel poor (%)", low="green",high="red")+
  labs(caption ="Solent (all LSOAs)")
head(lsoa_fuelpov_2019_merged)
names(lsoa_fuelpov_2019_merged)
```
#####Looking at the cities in more detail
```{r Southampton LSOA Fuel Pov 2019}
#Cities such as Southampton disappear due to their density, we will now map Southampton alone to see this area in more detail
mapData <- dplyr::filter(lsoa_fuelpov_2019_merged, LAD11NM == "Southampton")

# plotting the fuel poverty 2019 of Southampton in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = pcFP)) +
  scale_fill_continuous(name = "Proportions of households fuel poor (%)", low = "green", high = "red") +
  labs(caption = "Southampton")
```
```{r Portsmouth LSOA Fuel Pov 2019}
#Cities such as Portsmouth disappear due to their density, we will now map Portsmouth alone to see this area in more detail
mapData <- dplyr::filter(lsoa_fuelpov_2019_merged, LAD11NM == "Portsmouth")

# plotting the change in fuel poverty from 2018-2012 of Southampton in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = pcFP)) +
  scale_fill_continuous(name = "Proportions of households fuel poor (%)", low = "green", high = "red") +
  labs(caption = "Portsmouth")
```
```{r Winchester LSOA Fuel Pov}
#Cities such as Winchester disappear due to their density, we will now map Winchester alone to see this area in more detail
mapData <- dplyr::filter(lsoa_fuelpov_2019_merged, LAD11NM == "Winchester")

# plotting the fuel poverty 2019 of Winchester in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = pcFP)) +
  scale_fill_continuous(name = "Proportions of households fuel poor (%)", low = "green", high = "red") +
  labs(caption = "Winchester")
```

#### 2018
```{r Loading in the LSOA 2018 Fuel Poverty data}
inFile<-paste0(dataFolder, "Fuel Poverty/2018 LSOA_Fuel_Poverty.csv")
lsoa_fuelpov_2018<-readr::read_csv (inFile)
head(lsoa_fuelpov_2018)
```

```{r Mapping the LSOA 2018 Fuel Poverty}
lsoa_fuelpov_2018$LSOA11CD <- lsoa_fuelpov_2018$"LSOA Code" #creating a variable with the LSOA code in the same name as in sf_data
lsoa_fuelpov_2018_merged <- merge(lsoa_sf_data, lsoa_fuelpov_2018) #merging these
# as above - why does it load as a char?
lsoa_fuelpov_2018_merged$pcFP18 <- as.numeric(lsoa_fuelpov_2018_merged$`Proportion of households fuel poor (%)`)
ggplot2::ggplot(lsoa_fuelpov_2018_merged) +
  geom_sf(aes(fill=pcFP18))+ 
  scale_fill_continuous(name="Proportion of households fuel poor (%)", low="green",high="red")+
  labs(caption ="Solent (all LSOAs) 2018")
```
#####Looking at the cities in more detail
```{r Southampton LSOA Fuel Pov 2018}
#Cities such as Southampton disappear due to their density, we will now map Southampton alone to see this area in more detail
mapData <- dplyr::filter(lsoa_fuelpov_2018_merged, LAD11NM == "Southampton")

# plotting the fuel poverty 2019 of Southampton in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = pcFP18)) +
  scale_fill_continuous(name = "Proportions of households fuel poor (%)", low = "green", high = "red") +
  labs(caption = "Southampton 2018")
```
```{r Portsmouth LSOA Fuel Pov 2018}
#Cities such as Portsmouth disappear due to their density, we will now map Portsmouth alone to see this area in more detail
mapData <- dplyr::filter(lsoa_fuelpov_2018_merged, LAD11NM == "Portsmouth")

# plotting the change in fuel poverty from 2018-2012 of Southampton in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = pcFP18)) +
  scale_fill_continuous(name = "Proportions of households fuel poor (%)", low = "green", high = "red") +
  labs(caption = "Portsmouth 2018")
```
```{r Winchester LOSA Fuel Pov 2018}
#Cities such as Winchester disappear due to their density, we will now map Winchester alone to see this area in more detail
mapData <- dplyr::filter(lsoa_fuelpov_2018_merged, LAD11NM == "Winchester")
# plotting the fuel poverty 2019 of Winchester in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = pcFP18)) +
  scale_fill_continuous(name = "Proportions of households fuel poor (%)", low = "green", high = "red") +
  labs(caption = "Winchester 2018")
```
####Mapping the difference in proportion of fuel poverty from 2012 to 2018
```{r Creating the dfference in proportion variable}
#Green indicates a smaller increase in fuel poverty from 2012 to 2018
#Had to use 2018 as the metric for fuel poverty has changed in 2019 
#Red indicates an increase in fuel poverty from 2012 to 2018
fp_LSOA_2012_df <- readr::read_csv(paste0(dataFolder, "/Fuel Poverty/2012 LSOA_Fuel_Poverty.csv"))
fp_LSOA_2018_df <- readr::read_csv(paste0(dataFolder, "/Fuel Poverty/2018 LSOA_Fuel_Poverty.csv"))
fp_LSOA_2012_df$fp2012 <- fp_LSOA_2012_df$`Proportion of households fuel poor (%)`
fp_LSOA_2018_df$fp2018 <- fp_LSOA_2018_df$`Proportion of households fuel poor (%)`
merged_df <- merge(fp_LSOA_2012_df, fp_LSOA_2018_df, by = "LSOA Code", all = TRUE)
names(merged_df)
merged_df$fp_diff <-  as.numeric(merged_df$fp2018) - merged_df$fp2012
summary(merged_df)
```
```{r Mapping the change in Fuel Poverty}
merged_df$LSOA11CD <- merged_df$"LSOA Code" #creating a variable with the LSOA code in the same name as in sf_data
lsoa_fuelpov20122018 <- merge(lsoa_sf_data, merged_df) #merging these
ggplot2::ggplot(lsoa_fuelpov20122018) +
  geom_sf(aes(fill=fp_diff))+ 
  scale_fill_continuous(name="Change in Proportions of households fuel poor (%)", low="green",high="red")+
  labs(caption ="Solent (all LSOAs)")

#Histogram 
lsoa_fuelpov20122018$pc_diff <-100* (lsoa_fuelpov20122018$fp_diff/lsoa_fuelpov20122018$fp2012)
t_diff <-dplyr::select(as.data.frame(lsoa_fuelpov20122018),LSOA11CD, 'LSOA Code', fp2012, fp2018, fp_diff, pc_diff)
head(arrange(t_diff, pc_diff))
head(arrange(t_diff, -pc_diff))
ggplot2::ggplot(t_diff, aes(x=pc_diff)) +
  geom_histogram()
```
##### Looking at cities in more detail
```{r Southampton LSOA Fuel Pov 2012 2018}
#Cities such as Southampton disappear due to their density, we will now map Southampton alone to see this area in more detail
mapData <- dplyr::filter(lsoa_fuelpov20122018, LAD11NM == "Southampton")

# plotting the change in fuel poverty from 2018-2012 of Southampton in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = pc_diff)) +
  scale_fill_continuous(name = "Change in Proportions of households fuel poor (%)", low = "green", high = "red") +
  labs(caption = "Southampton")
#Around Bargate and Freemantle increased fuel poverty
```
```{r Portsmouth LSOA Fuel Pov 2012 2018}
#Cities such as Portsmouth disappear due to their density, we will now map Portsmouth alone to see this area in more detail
mapData <- dplyr::filter(lsoa_fuelpov20122018, LAD11NM == "Portsmouth")

# plotting the change in fuel poverty from 2018-2012 of Portsmouth in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = pc_diff)) +
  scale_fill_continuous(name = "Change in Proportions of households fuel poor (%)", low = "green", high = "red") +
  labs(caption = "Portsmouth")
#Charles Dickens increased fuel poverty
```
```{r Winchester LSOA Fuel Pov 2012 2018}
#Cities such as Winchester disappear due to their density, we will now map Winchester alone to see this area in more detail
mapData <- dplyr::filter(lsoa_fuelpov20122018, LAD11NM == "Winchester")

# plotting the change in fuel poverty from 2018-2012 of Winchester in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = pc_diff)) +
  scale_fill_continuous(name = "Change in Proportions of households fuel poor (%)", low = "green", high = "red") +
  labs(caption = "Winchester")
```
### Over 65 annd Fuel Poverty
```{r Loading in the Census age data}
inFile<-paste0(dataFolder, "census/KS102EW-age-categories.csv")
census_age<-readr::read_csv (inFile)
census_age$'LSOA11CD'<- census_age$'geography code'
head(census_age)
names(census_age)
```
```{r Plotting the fuel poverty in over 65s}
#census_age$"LSOA11CD" <- census_age$"geography code"
Census_age_fp <- merge(lsoa_fuelpov_2019, census_age, by = "LSOA11CD")
names(Census_age_fp)
# select the variables we want for clarity
df <- dplyr::select(Census_age_fp, LSOA11CD, "LA Name", "Proportion of households fuel poor (%)", "Proportion Over 65")

head(df)
table(df$`LA Name`)
Solent <- dplyr::filter(df, `LA Name` == "Basingstoke and Deane"|
                           `LA Name` == "East Hampshire"|
                           `LA Name` == "Eastleigh"|
                           `LA Name` == "Fareham"|
                           `LA Name` == "Gosport"|
                           `LA Name` == "Hart"|
                           `LA Name` == "Havant"|
                           `LA Name` == "New Forest"|
                           `LA Name` == "Portsmouth"|
                           `LA Name` == "Rushmoor"|
                           `LA Name` == "Southampton"|
                           `LA Name` == "Test Valley"|
                           `LA Name` == "Winchester"|
                           `LA Name` == "Isle of Wight"
                           )

# select the places we want here
ggplot(Solent, aes(x=`Proportion Over 65`, y=`Proportion of households fuel poor (%)`)) +
  geom_point()
nrow(Solent)
table(Solent$`LA Name`)
  
```











