---
title: "LSOA domestic Electricty and Gas maps"
author: "Meghan Kinglsey-Walsh"
date: 'Last run at: `r Sys.time()`'
output:
  bookdown::html_document2:
    fig_caption: yes
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 4
    toc_float: TRUE
  bookdown::pdf_document2:
    toc: yes
    fig_caption: yes
    number_sections: yes
  bookdown::word_document2: 
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 4
    fig_width: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) # set this to FALSE if you don't want the code in the final output

# useful R libraries
library(ggplot2)
library(readr)
library(dplyr)

# GIS libraries
library(raster)
library(sf)
library(spData)
library(spDataLarge)

dataFolder<-"/Users/megha/Desktop/1. Uni/Masters/Project/Mapping Code/data/" # default for Meghan
user <- Sys.info()[[7]] # who are we logged in as?
if(user == "ben"){
  dataFolder <- path.expand("~/University of Southampton/HCC Energy Landscape Mapping project - Documents/General/data/")
}

# this will not print anything out when knitted due to the include=FALSE setting in the chunk header
message("User: ", user)
message("dataFolder: ", dataFolder)
```


# Mapping the Lower Layer Super Output Area (LSOA)
## Mapping Domestic
### Mapping Electricity consumption
####2019
```{r Loading in the LSOA electricty consumption data}
#Electricty consumption data LSOA pre downloaded
inFile <-paste0(dataFolder, "energy/electricity/LSOA Dom Elec csv/LSOA_ELEC_2019.csv")
lsoa_elecData <- readr::read_csv(inFile)
lsoa_elecData$LSOA11CD <- lsoa_elecData$`Lower Layer Super Output Area (LSOA) Code`
head(lsoa_elecData)
```

```{r Loading in boundary data for the LSOA}
#The LSOA boundaries for the Solent have been pre-downloaded
inf<-paste0(dataFolder, "boundaries/LSOA/lsoa_solent.shp")
message ("Loading LSOA boundaries from file")
lsoa_sf_data <- sf::read_sf(inf)
head(lsoa_sf_data)
table(lsoa_sf_data$LAD11NM)#How many LSOAs are there in each LA
```

```{r Mapping the electricty consumption of the LSOAs}
lsoa_merged_sf <- merge(lsoa_sf_data, lsoa_elecData) #merging the boundaries and energy data
ggplot2::ggplot(lsoa_merged_sf) + 
  geom_sf(aes(fill = `Mean domestic electricity consumption \n(kWh per meter)`)) +
  scale_fill_continuous(name = "Mean kWh per meter", low = "green", high = "red") +
  labs(caption = "Solent (all LSOAs)")
#Mapping it
```

##### Looking at cities in more detail        
```{r Southampton LSOA dom Elec}
#Cities such as Southampton disappear due to their density, we will now map Southampton alone to see this area in more detail
mapData <- dplyr::filter(lsoa_merged_sf, LAD11NM == "Southampton")
# plotting the electricity consumption of Southampton in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = `Mean domestic electricity consumption \n(kWh per meter)`)) +
  scale_fill_continuous(name = "Mean kWh per meter", low = "green", high = "red") +
  labs(caption = "Southampton")
```
```{r Portsmouth LSOA dom Elec}
#Cities such as Portsmouth disappear due to their density, we will now map Portsmouth alone to see this area in more detail
mapData <- dplyr::filter(lsoa_merged_sf, LAD11NM == "Portsmouth")
# plotting the electricity consumption of Portsmouth in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = `Mean domestic electricity consumption \n(kWh per meter)`)) +
  scale_fill_continuous(name = "Mean kWh per meter", low = "green", high = "red") +
  labs(caption = "Portsmouth")
```
```{r Winchester LSOA dom Elec}
#Cities such as Winchester disappear due to their density, we will now map Winchester alone to see this area in more detail
mapData <- dplyr::filter(lsoa_merged_sf, LAD11NM == "Winchester")

# plotting the electricity consumption of Winchester in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = `Mean domestic electricity consumption \n(kWh per meter)`)) +
  scale_fill_continuous(name = "Mean kWh per meter", low = "green", high = "red") +
  labs(caption = "Winchester")
```
####Difference between 2010 and 2019 dom elec
```{r Creating the difference in LSOA mean dom elec consumption variable}
domelec_LSOA_2010 <- readr::read_csv(paste0(dataFolder,"energy/electricity/LSOA Dom Elec csv/LSOA_ELEC_2010.csv"))
domelec_LSOA_2019 <- readr::read_csv(paste0(dataFolder, "energy/electricity/LSOA Dom Elec csv/LSOA_ELEC_2019.csv"))
domelec_LSOA_2010$de2010 <- domelec_LSOA_2010$'Mean domestic electricity consumption \n(kWh per meter)'
domelec_LSOA_2019$de2019 <- domelec_LSOA_2019$'Mean domestic electricity consumption \n(kWh per meter)'
# create unambiguos lsoa code for matching to each other and the sf geometry
domelec_LSOA_2010$LSOA11CD <- domelec_LSOA_2010$`Lower Layer Super Output Area (LSOA) Code`
domelec_LSOA_2019$LSOA11CD <- domelec_LSOA_2019$`Lower Layer Super Output Area (LSOA) Code`
  
merged_de <- merge(domelec_LSOA_2010, domelec_LSOA_2019, by="LSOA11CD", all=TRUE)
names(merged_de)
merged_de$de_diff<-as.numeric(merged_de$de2019)-as.numeric(merged_de$de2010) ##Fixed
summary(merged_de)
```

```{r Mapping the LSOA difference in mean dom elec consumption}
# merge to sf geometry on LSOA11CD
lsoa_sf_de20102019<-merge(lsoa_sf_data, merged_de)
ggplot2::ggplot(lsoa_sf_de20102019, aes(fill=de_diff))+
                  geom_sf() +
                  scale_fill_continuous(name="Change in Mean comsumpton (kWh per meter)",low="green",high="red") +
  labs(caption="Solent(all LSOAs)")

lsoa_sf_de20102019$pc_diff <- 100*(lsoa_sf_de20102019$de_diff/lsoa_sf_de20102019$de2010)
t_diff <-  dplyr::select(as.data.frame(lsoa_sf_de20102019), 
                         LSOA11CD, `Lower Layer Super Output Area (LSOA) Name.y`,
                         de2010, de2019, de_diff, pc_diff)
head(arrange(t_diff, pc_diff))
head(arrange(t_diff, -pc_diff))
ggplot2::ggplot(t_diff, aes(x = pc_diff)) +
  geom_histogram()
```

#####Cities in more detail
```{r Southampton LSOA difference in dom Elec}
#Cities such as Southampton disappear due to their density, we will now map Southampton alone to see this area in more detail
mapData <- dplyr::filter(merged_de, LSOA11CD == "Southampton")
# plotting the electricity consumption of Southampton in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = `de_diff`)) +
  scale_fill_continuous(name = "Change in Mean comsumpton (kWh per meter)", low = "green", high = "red") +
  labs(caption = "Southampton")
#BROKEN
```
```{r Portsmouth LSOA difference in dom Elec}
#Cities such as Portsmouth disappear due to their density, we will now map Portsmouth alone to see this area in more detail
mapData <- dplyr::filter(merged_de, LAD11NM == "Portsmouth")
# plotting the electricity consumption of Portsmouth in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = `de-diff`)) +
  scale_fill_continuous(name = "Change in Mean comsumpton (kWh per meter)", low = "green", high = "red") +
  labs(caption = "Portsmouth")
```
```{r Winchester LSOA difference in dom Elec}
#Cities such as Winchester disappear due to their density, we will now map Winchester alone to see this area in more detail
mapData <- dplyr::filter(merged_de, LAD11NM == "Winchester")
# plotting the electricity consumption of Winchester in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = `de_diff`)) +
  scale_fill_continuous(name = "Change in Mean comsumpton (kWh per meter)", low = "green", high = "red") +
  labs(caption = "Winchester")
```

### Mapping Gas
####2019
```{r Loading in the LSOA gas consumption data}
#Electricty consumption data LSOA pre downloaded
inFile <-paste0(dataFolder, "energy/gas/LSOA Gas csv/LSOA_GAS_2019.csv")
lsoa_gasData <- readr::read_csv(inFile)
lsoa_gasData$LSOA11CD <- lsoa_gasData$`Lower Layer Super Output Area (LSOA) Code`
head(lsoa_gasData)
```

```{r Mapping the gas consumption of the LSOAs}
lsoa_merged_sf_gas <- merge(lsoa_sf_data, lsoa_gasData) #merging the boundaries and energy data
ggplot2::ggplot(lsoa_merged_sf_gas) + 
  geom_sf(aes(fill = `Mean consumption (kWh per meter)`)) +
  scale_fill_continuous(name = "Gas: Mean kWh per meter", low = "green", high = "red") +
  labs(caption = "Solent (all LSOAs)")
#Mapping it
```
> Aha - this one shows where there is no gas :-)

#####Cities in More detail
```{r Southampton LSOA Gas}
#Cities such as Southampton disappear due to their density, we will now map Southampton alone to see this area in more detail
mapData <- dplyr::filter(lsoa_merged_sf_gas, LAD11NM == "Southampton")

# plotting the gas consumption of Southampton in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = `Mean consumption (kWh per meter)`)) +
  scale_fill_continuous(name = "Gas: Mean kWh per meter", low = "green", high = "red") +
  labs(caption = "Southampton")
```
```{r Portsmouth LSOA Gas}
#Cities such as Portsmouth disappear due to their density, we will now map Portsmouth alone to see this area in more detail
mapData <- dplyr::filter(lsoa_merged_sf_gas, LAD11NM == "Portsmouth")

# plotting the gas consumption of Portsmouth in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = `Mean consumption (kWh per meter)`)) +
  scale_fill_continuous(name = "Gas: Mean kWh per meter", low = "green", high = "red") +
  labs(caption = "Portsmouth")
```
```{r Winchester LSOA Gas}
#Cities such as Winchester disappear due to their density, we will now map Winchester alone to see this area in more detail
mapData <- dplyr::filter(lsoa_merged_sf_gas, LAD11NM == "Winchester")

# plotting the gas consumption of Winchester in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = `Mean consumption (kWh per meter)`)) +
  scale_fill_continuous(name = "Gas: Mean kWh per meter", low = "green", high = "red") +
  labs(caption = "Winchester")
```
####Difference between 2010 and 2019 dom gas 
```{r Creating the dfference in LSOA dom gas consumption variable}
#Green indicates a decrease in gas consumption from 2010 to 2019
#Red indicates an increase in gas consumption from 2010 to 2019
dgas_LSOA_2010 <- readr::read_csv(paste0(dataFolder, "energy/gas/LSOA Gas csv/LSOA_GAS_2010.csv"))
dgas_LSOA_2019 <- readr::read_csv(paste0(dataFolder, "energy/gas/LSOA Gas csv/LSOA_GAS_2019.csv"))
dgas_LSOA_2010$dgas2010 <- dgas_LSOA_2010$`Mean consumption (kWh per meter)`
dgas_LSOA_2019$dgas2019 <- dgas_LSOA_2019$`Mean consumption (kWh per meter)`
merged_dgas <- merge(dgas_LSOA_2010, dgas_LSOA_2019, by = "Middle Layer Super Output Area (MSOA) Code", all = TRUE)
names(merged_dgas)
merged_dgas$dg_diff<-as.numeric(merged_dgas$dgas2019) - merged_dgas$dgas2010
summary(merged_dgas)
```

```{r Mapping the change in LSOA dom mean gas comsumption}
merged_dgas$LSOA11CD <- merged_dgas$"Middle Layer Super Output Area (MSOA) Code" #creating a variable with the LSOA code in the same name as in sf_data
lsoa_dgas20102019 <- merge(lsoa_sf_data, merged_dgas) #merging these
ggplot2::ggplot(merged_dgas) +
  geom_sf(aes(fill=dg_diff))+ 
  scale_fill_continuous(name="Change in Gas: Mean kWh per meter", low="green",high="red")+
  labs(caption ="Solent (all MSOAs)") ##BROKEN
```

#####Cities in more detail
```{r Southampton LSOA Gas}
#Cities such as Southampton disappear due to their density, we will now map Southampton alone to see this area in more detail
mapData <- dplyr::filter(lsoa_merged_sf_gas, LAD11NM == "Southampton")

# plotting the gas consumption of Southampton in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = `Mean consumption (kWh per meter)`)) +
  scale_fill_continuous(name = "Gas: Mean kWh per meter", low = "green", high = "red") +
  labs(caption = "Southampton")
```
```{r Portsmouth LSOA Gas}
#Cities such as Portsmouth disappear due to their density, we will now map Portsmouth alone to see this area in more detail
mapData <- dplyr::filter(lsoa_merged_sf_gas, LAD11NM == "Portsmouth")

# plotting the gas consumption of Portsmouth in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = `Mean consumption (kWh per meter)`)) +
  scale_fill_continuous(name = "Gas: Mean kWh per meter", low = "green", high = "red") +
  labs(caption = "Portsmouth")
```
```{r Winchester LSOA Gas}
#Cities such as Winchester disappear due to their density, we will now map Winchester alone to see this area in more detail
mapData <- dplyr::filter(lsoa_merged_sf_gas, LAD11NM == "Winchester")

# plotting the gas consumption of Winchester in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = `Mean consumption (kWh per meter)`)) +
  scale_fill_continuous(name = "Gas: Mean kWh per meter", low = "green", high = "red") +
  labs(caption = "Winchester")
```

