---
title: "MSOA Industrial Electricty and Gas maps"
author: "Meghan Kinglsey-Walsh"
date: 'Last run at: `r Sys.time()`'
output:
  bookdown::html_document2:
    fig_caption: yes
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 4
    toc_float: TRUE
  bookdown::pdf_document2:
    toc: yes
    fig_caption: yes
    number_sections: yes
  bookdown::word_document2: 
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 4
    fig_width: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) # set this to FALSE if you don't want the code in the final output

# useful R libraries
library(ggplot2)
library(readr)
library(dplyr)

# GIS libraries
library(raster)
library(sf)
#library(spData)
#library(spDataLarge)

dataFolder<-"/Users/megha/Desktop/1. Uni/Masters/Project/Mapping Code/data/" # default for Meghan
user <- Sys.info()[[7]] # who are we logged in as?
if(user == "ben"){
  dataFolder <- path.expand("~/University of Southampton/HCC Energy Landscape Mapping project - Documents/General/data/")
}

# this will not print anything out when knitted due to the include=FALSE setting in the chunk header
message("User: ", user)
message("dataFolder: ", dataFolder)
```
# Background Data
```{r Loading in the Boundary Data for the MSOA}
inf <-paste0(dataFolder, "boundaries/MSOA/msoa_solent.shp")
message("Loading Middle Layer Super Output Area (MSOA) from file")
#When using shp files you might also need to have other supplementary files in the same folder to allow it to run https://cfss.uchicago.edu/notes/simple-features/
msoa_sf_data <- sf::read_sf(inf) 
head (msoa_sf_data)
table(msoa_sf_data$LAD11NM)#how many MSOAs are in each LA
```
# Mapping Electricty
##2019
```{r Loading in the MSOA electricity consumption data for industry }
# electricity consumption data for industry at MSOA level (pre downloaded)
inFile <-paste0(dataFolder, "energy/electricity/MSOA NonDom Elec csv/MSOA_NONDOM_2019.csv")
msoa_elecDatanondom <- readr::read_csv(inFile)
head(msoa_elecDatanondom)
```

```{r Mapping the electrcity consumption of the MSOAs Industrial Sector}
msoa_elecDatanondom$MSOA11CD <- msoa_elecDatanondom$ 'Middle Layer Super Output Area (MSOA) Code' 
msoa_merged_sf_nondom <-merge(msoa_sf_data, msoa_elecDatanondom)
ggplot2::ggplot(msoa_merged_sf_nondom) + 
  geom_sf(aes(fill = `Mean consumption (kWh per meter)`)) +
  scale_fill_continuous(name = "Electricity: Mean kWh per meter", low = "green", high = "red") +
  labs(caption = "Solent (all MSOAs)")
#mapping it
mean(msoa_merged_sf_nondom$`Mean consumption (kWh per meter)`)
```
###Map Overlay
```{r Check leaflet for non dom elec consumption}
library (leaflet)

st_coord_sys <- st_crs(msoa_merged_sf_nondom)
st_coord_sys$epsg
#current coordinate system 27700 Leaflet needs EPSG: 4326 

#Transforming the coor system
if(st_coord_sys$epsg !=4326) {
  map_df_trans <- st_transform(msoa_merged_sf_nondom, "+proj=longlat +datum=WGS84")
}

```
```{r Plotting leaflet non dom elec consumption map}
qpal <- colorNumeric("Reds", map_df_trans$`Mean consumption (kWh per meter)`, n=9)

leaflet(map_df_trans) %>%
  addTiles() %>% 
  addPolygons(color= ~qpal(`Mean consumption (kWh per meter)`), 
              fillOpacity = 0.6, weight = 1.5, popup= ~(MSOA11CD),
                        
                highlight = highlightOptions(
                weight = 5,
                color = "#666",
                fillOpacity = 0.7,
                bringToFront = TRUE))

```
##Difference from 2010 to 2019
```{r Creating the mean electricty consumption from the industrial sector MOSA}
ndelec_msoa_2010<-readr::read_csv(paste0(dataFolder,"energy/electricity/MSOA NonDom Elec csv/MSOA_NONDOM_2010.csv"))
ndelec_msoa_2019<-readr::read_csv(paste0(dataFolder,"/energy/electricity/MSOA NonDom Elec csv/MSOA_NONDOM_2019.csv"))
ndelec_msoa_2010$ndelec2010<-ndelec_msoa_2010$'Mean consumption (kWh per meter)'                                       
ndelec_msoa_2019$ndelec2019<-ndelec_msoa_2019$'Mean consumption (kWh per meter)'
merged_ndelec<-merge(ndelec_msoa_2010, ndelec_msoa_2019, by = "Middle Layer Super Output Area (MSOA) Code", all=TRUE)
names(merged_ndelec)
merged_ndelec$ndelec_diff<-(as.numeric(merged_ndelec$ndelec2019))-(as.numeric(merged_ndelec$ndelec2010))
summary(merged_ndelec)
```

```{r Mapping the difference in mean electricty consumption from the industrial sector MOSA}
merged_ndelec$MSOA11CD<-merged_ndelec$"Middle Layer Super Output Area (MSOA) Code"
msoa_nd20102019<-merge(msoa_sf_data, merged_ndelec) #merging these
ggplot2::ggplot(msoa_nd20102019)+geom_sf(aes(fill=ndelec_diff))+scale_fill_continuous(name="Change in electricty:Mean kWh per meter",low="green",high="red")+labs(caption ="Solent (all MSOAs)")

msoa_nd20102019$pc_diff <-100*(msoa_nd20102019$ndelec_diff/msoa_nd20102019$ndelec2010)
t_diff <- dplyr::select(as.data.frame(msoa_nd20102019),MSOA11CD, 'Middle Layer Super Output Area (MSOA) Code', ndelec2010, ndelec2019,ndelec_diff, pc_diff)
head(arrange(t_diff, pc_diff))
head(arrange(t_diff, -pc_diff))
ggplot2::ggplot(t_diff, aes(x=pc_diff)) +
  geom_histogram()
```
###Map with Overlay
```{r Check leaflet for change in non dom elec consumption}
library(leaflet)

st_coord_sys <- st_crs(msoa_nd20102019)
st_coord_sys$epsg
#Current coor system 27700 Leaflet wants EPSG: 4326 so we need to transform

#Tranforming the coord system
if(st_coord_sys$epsg !=4326){
  map_df_trans <- st_transform(msoa_nd20102019, "+proj=longlat +datum=WGS84")
}
```
```{r Plotting leaflet change in non dom elec consumtpion map}
qpal <- colorNumeric("Reds", map_df_trans$ndelec_diff, n=9)

leaflet(map_df_trans) %>%
  addTiles() %>%
  addPolygons(color = ~qpal(ndelec_diff),
              fillOpacity = 0.6, weight = 1.5, popup = ~(MSOA11CD), 
               highlight = highlightOptions(
                weight = 5,
                color = "#666",
                fillOpacity = 0.7,
                bringToFront = TRUE))

```
```{r Mapping the percentage change in mean electricty consumption from the industrial sector MOSA}
merged_ndelec$MSOA11CD<-merged_ndelec$"Middle Layer Super Output Area (MSOA) Code"
msoa_nd20102019<-merge(msoa_sf_data, merged_ndelec) #merging these
ggplot2::ggplot(msoa_nd20102019)+geom_sf(aes(fill=ndelec_diff/ndelec2010))+scale_fill_continuous(name="Change in electricty:Mean kWh per meter",low="green",high="red")+labs(caption ="Solent (all MSOAs)")##Why does this look like this? Increased efficiency? Businesses closing down?
```
###Cities in more detail
```{r Southampton MSOA difference in non dom Elec}
#Cities such as Southampton disappear due to their density, we will now map Southampton alone to see this area in more detail
mapData <- dplyr::filter(msoa_nd20102019, LAD11NM == "Southampton")
# plotting the electricity consumption of Southampton in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = ndelec_diff/ndelec2010)) +
  scale_fill_continuous(name = "Change in Mean comsumpton (kWh per meter)", low = "green", high = "red") +
  labs(caption = "Southampton")
```
```{r Portsmouth LSOA difference in dom Elec}
#Cities such as Portsmouth disappear due to their density, we will now map Portsmouth alone to see this area in more detail
mapData <- dplyr::filter(msoa_nd20102019, LAD11NM == "Portsmouth")
# plotting the electricity consumption of Portsmouth in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = ndelec_diff/ndelec2010)) +
  scale_fill_continuous(name = "Change in Mean comsumpton (kWh per meter)", low = "green", high = "red") +
  labs(caption = "Portsmouth")
```
```{r Winchester LSOA difference in dom Elec}
#Cities such as Winchester disappear due to their density, we will now map Winchester alone to see this area in more detail
mapData <- dplyr::filter(msoa_nd20102019, LAD11NM == "Winchester")
# plotting the electricity consumption of Winchester in more detail
ggplot2::ggplot(mapData) + 
  geom_sf(aes(fill = ndelec_diff/ndelec2010)) +
  scale_fill_continuous(name = "Change in Mean comsumpton (kWh per meter)", low = "green", high = "red") +
  labs(caption = "Winchester")
```
# Mapping Gas
##2019
```{r Loading in the MSOA gas consumption data for industry }
# gas consumption data for industry at MSOA level (pre downloaded)
inFile <-paste0(dataFolder, "energy/gas/MSOA NonDom Gas csv/MSOA_NonDom_Gas_2019.csv")
msoa_ndgas <- readr::read_csv(inFile)
head(msoa_ndgas)
```

```{r Mapping the gas consumption of the MSOAs Industrial Sector}
msoa_ndgas$MSOA11CD <- msoa_ndgas$'Middle Layer Super Output Area (MSOA) Code' 
msoa_merged_ndgas <-merge(msoa_sf_data, msoa_ndgas)
ggplot2::ggplot(msoa_merged_ndgas) + 
  geom_sf(aes(fill = `Mean consumption (kWh per meter)`)) +
  scale_fill_continuous(name = "Gas: Mean kWh per meter", low = "green", high = "red") +
  labs(caption = "Solent (all MSOAs)")
#mapping it
```
> The holes tell you where there is no non-domestic gas use

##Mapping the difference in non domestic gas from 2010 to 2019 
```{r Creating the difference in non domestic gas consumption in the MSOA}
msoa_2010_ndgas<-readr::read_csv(paste0(dataFolder,"/energy/gas/MSOA NonDom Gas csv/MSOA_NonDom_Gas_2010.csv"))
msoa_2019_ndgas<-readr::read_csv(paste0(dataFolder,"energy/gas/MSOA NonDom Gas csv/MSOA_NonDom_Gas_2019.csv"))
msoa_2010_ndgas$ndgas2010<-msoa_2010_ndgas$'Mean consumption (kWh per meter)'
msoa_2019_ndgas$ndgas2019<-msoa_2019_ndgas$'Mean consumption (kWh per meter)'

msoa_2010_ndgas$MSOA11CD <-msoa_2010_ndgas$'Middle Layer Super Output Area (MSOA) Code'
msoa_2019_ndgas$MSOA11CD <-msoa_2019_ndgas$'Middle Layer Super Output Area (MSOA) Code'

merged_ndgas<-merge(msoa_2010_ndgas, msoa_2019_ndgas, by = "Middle Layer Super Output Area (MSOA) Code", all=TRUE)
names(merged_ndgas)
merged_ndgas$ndgas_diff<-merged_ndgas$ndgas2019 - merged_ndgas$ndgas2010 
summary(merged_ndgas)
```

```{r Mapping the change in non domestic gas usage in the MSOA}
merged_ndgas$MSOA11CD <- merged_ndgas$"Middle Layer Super Output Area (MSOA) Code" #creating a variable with the LSOA code in the same name as in sf_data

msoa_ndgas20102019 <- merge(msoa_sf_data, merged_ndgas) #merging these
ggplot2::ggplot(msoa_ndgas20102019) +
  geom_sf(aes(fill=ndgas_diff))+ 
  scale_fill_continuous(name="Change in mean gas consumption in the indistrial sector", low="green",high="red")+
  labs(caption ="Solent (all MSOAs)")

msoa_ndgas20102019$pc_diff <-100*(msoa_ndgas20102019$ndgas_diff/msoa_ndgas20102019$ndgas2010)
t_diff <- dplyr::select(as.data.frame(msoa_ndgas20102019), MSOA11CD, 'Middle Layer Super Output Area (MSOA) Code', ndgas2010, ndgas2019, ndgas_diff, pc_diff) 
head(arrange(t_diff, pc_diff))
head(arrange(t_diff, -pc_diff))
ggplot2::ggplot(t_diff, aes(x=pc_diff))+
  geom_histogram()

```
###Map with Overlay
```{r Check leaflet for Change in non dom gas consumption}
library(leaflet)

st_coord_sys <- st_crs(msoa_ndgas20102019)
st_coord_sys$epsg

#Transporting the coord system
if(st_coord_sys$epsg !=4326){
  map_df_trans <- st_transform(msoa_ndgas20102019, "+proj=longlat +datum=WGS84")
}
```
```{r Plotting leaflet change in non dom gas consumption map}
qpal <- colorNumeric("Reds", map_df_trans$ndgas_diff, n=9)

leaflet(map_df_trans) %>%
  addTiles() %>%
  addPolygons(color=~qpal(ndgas_diff),
              fillOpacity = 0.6, weight = 1.5, popup = ~(MSOA11CD), 
             
  
               highlight = highlightOptions(
                weight = 5,
                color = "#666",
                fillOpacity = 0.7,
                bringToFront = TRUE))

```

