---
title: "Solent region: Test Maps"
author: "Meghan Kinglsey-Walsh"
date: 'Last run at: `r Sys.time()`'
output:
  bookdown::html_document2:
    fig_caption: yes
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 4
    toc_float: TRUE
  bookdown::pdf_document2:
    toc: yes
    fig_caption: yes
    number_sections: yes
  bookdown::word_document2: 
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 4
    fig_width: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) # set this to FALSE if you don't want the code in the final output

# useful R libraries
library(ggplot2)
library(readr)
library(dplyr)

# GIS libraries
library(raster)
library(sf)
library(spData)
library(spDataLarge)

dataFolder<-"/Users/megha/Desktop/1. Uni/Masters/Project/Mapping Code/data/" # default for Meghan
user <- Sys.info()[[7]] # who are we logged in as?
if(user == "ben"){
  dataFolder <- path.expand("~/University of Southampton/HCC Energy Landscape Mapping project - Documents/General/data/")
}

# this will not print anything out when knitted due to the include=FALSE setting in the chunk header
message("User: ", user)
message("dataFolder: ", dataFolder)
```

# Mapping the Middle Layer Super Output Areas (MSOA)
## Mapping Domestic
### Mapping the Electricity Consumption
####2019
```{r Loading in the MSOA electricity consumption data}
# electricity consumption data at MSOA level (pre downloaded)
inFile <-paste0(dataFolder, "energy/MSOA_DOM_ELEC_2019.csv")
msoa_elecData <- readr::read_csv(inFile)
head(msoa_elecData)
```

```{r Loading in the Boundary Data for the MSOA}
inf <-paste0(dataFolder, "boundaries/MSOA/msoa_solent.shp")
message("Loading Middle Layer Super Output Area (MSOA) from file")
#When using shp files you might also need to have other supplementary files in the same folder to allow it to run https://cfss.uchicago.edu/notes/simple-features/
msoa_sf_data <- sf::read_sf(inf) 
head (msoa_sf_data)
table(msoa_sf_data$LAD11NM)#how many MSOAs are in each LA
```

```{r Mapping the electrcity consumption of the MSOAs}
msoa_elecData$MSOA11CD <- msoa_elecData$ 'Middle Layer Super Output Area (MSOA) Code' #Creating a variable with the LA code and the name as in the sf_data
msoa_merged_sf <-merge(msoa_sf_data, msoa_elecData)
ggplot2::ggplot(msoa_merged_sf) + 
  geom_sf(aes(fill = `Mean consumption (kWh per meter)`)) +
  scale_fill_continuous(name = "Electricity: Mean kWh per meter", low = "green", high = "red") +
  labs(caption = "Solent (all MSOAs)")
#mapping it
```
####Mapping the change from 2010 to 2019
```{r Creating the difference in MSOA mean dom elec consumption variable}
domelec_MSOA_2010<-readr::read_csv(paste0(dataFolder,"/energy/MSOA_DOM_ELEC_2010.csv"))
domelec_MSOA_2019<-readr::read_csv(paste0(dataFolder, "/energy/MSOA_DOM_ELEC_2019.csv"))
domelec_MSOA_2010$domelec2010<-domelec_MSOA_2010$'Mean consumption (kWh per meter)'
domelec_MSOA_2019$domelec2019<-domelec_MSOA_2019$'Mean consumption (kWh per meter)'
merged_domelec<-merge(domelec_MSOA_2010, domelec_MSOA_2019, by="Middle Layer Super Output Area (MSOA) Code", all=TRUE) ##BROKEN
names(merged_domelec)
merged_domelec$domelec_diff<-merged_domelec$domelec2019 - merged_domelec$domelec2010
summary(merged_domelec)
```
```{r Mapping the MSOA difference in mean dom elec consumption}
merged_domelec$MSOA11CD<-merged_domelec$"Middle Layer Super Output Area (MSOA) Code"
msoa_domelec20102019<-merge(msoa_sf_data, merged_domelec)
ggplot2::ggplot(msoa_domelec20102019)+geom_sf(aes(fill=domelec_diff))+scale_fill_continuous(name="Change in Mean comsumpton of domestic electricty per meter (kWh per meter",low="green",high="red")+labs(caption="Solent(all MSOAs)")
```

### Mapping the Gas
####2019
```{r Loading in the MSOA gas consumption data}
# gas consumption data at MSOA level (pre downloaded)
inFile <-paste0(dataFolder, "energy/MSOA_GAS_2019.csv")
msoa_gasData <- readr::read_csv(inFile)
head(msoa_gasData)
```
```{r Mapping the gas consumption of the MSOAs}
msoa_gasData$MSOA11CD <- msoa_gasData$ 'Middle Layer Super Output Area (MSOA) Code' 
msoa_merged_sf_domgas <-merge(msoa_sf_data, msoa_gasData)
ggplot2::ggplot(msoa_merged_sf_domgas) + 
  geom_sf(aes(fill = `Mean consumption (kWh per meter)`)) +
  scale_fill_continuous(name = "Gas: Mean kWh per meter", low = "green", high = "red") +
  labs(caption = "Solent (all MSOAs)")
#mapping it
```
> Does this match to non-gas areas??

####Mapping the change in gas consumption from 2010 to 2019
```{r Creating the dfference in consumption variable}
#Green indicates a decrease in gas consumption from 2010 to 2019
#Red indicates an increase in gas consumption from 2010 to 2019
domgas_MSOA_2010 <- readr::read_csv(paste0(dataFolder, "/energy/MSOA_GAS_2010.csv"))
domgas_MSOA_2019 <- readr::read_csv(paste0(dataFolder, "/energy/MSOA_GAS_2019.csv"))
domgas_MSOA_2010$domgas2010 <- domgas_MSOA_2010$`Mean consumption (kWh per meter)`
domgas_MSOA_2019$domgas2019 <- domgas_MSOA_2019$`Mean consumption (kWh per meter)`
merged_domgas <- merge(domgas_MSOA_2010, domgas_MSOA_2019, by = "Middle Layer Super Output Area (MSOA) Code", all = TRUE)
names(merged_domgas)
merged_domgas$mc_diff <-  as.numeric(merged_domgas$domgas2019) - merged_domgas$domgas2010
summary(merged_domgas)
```

```{r Mapping the change in dom mean gas comsumption}
merged_domgas$MSOA11CD <- merged_domgas$"MSOA Code" #creating a variable with the LSOA code in the same name as in sf_data
msoa_domgas20102019 <- merge(msoa_sf_data, merged_domgas) #merging these
ggplot2::ggplot(msoa_domgas20102019) +
  geom_sf(aes(fill=mc_diff))+ 
  scale_fill_continuous(name="Change in Gas: Mean kWh per meter", low="green",high="red")+
  labs(caption ="Solent (all MSOAs)")
##BROKEN
```


